# Generated by Django 3.2.5 on 2021-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210721_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='images/hero-bg.jpg', upload_to='media/blogs/%Y/%m/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('codeing', 'codeing'), ('Tech', 'Tech'), ('Info', 'Info'), ('Travel', 'Travel')], default='Uncategorised', max_length=255),
        ),
    ]
