# Generated by Django 3.2.5 on 2021-07-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_featured',
        ),
    ]
